backend:
  name: github
  repo: 0x0m0t0/astro-sveltia
  # branch: main
  branch: sveltia-vercel
  site_domain: astro-sveltia.vercel.app
  # base_url: https://netlify-cms-oauth-eight.vercel.app
  base_url: https://sveltia-cms-auth.cheguez.workers.dev

local_backend: true

media_folder: 'public/images/uploads'
public_folder: '/'

# collections:
#   - name: "blog" # Used in routes, e.g., /admin/collections/blog
#     label: "Blog" # Used in the UI
#     folder: "_posts/blog" # The path to the folder where the documents are stored
#     create: true # Allow users to create new documents in this collection
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#     fields: # The fields for each document, usually in front matter
#       - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
#       - { label: "Title", name: "title", widget: "string" }
#       - { label: "Publish Date", name: "date", widget: "datetime" }
#       - { label: "Featured Image", name: "thumbnail", widget: "image" }
#       - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
#       - { label: "Body", name: "body", widget: "markdown" }

# The CMS collections and their fields
collections:
  - name: 'blog'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'src/content/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          search_fields: 'name',
          value_field: 'name'
        }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          default: ['post'],
          hint: 'Enter tags separated by a comma'
        }
      - label: 'Image'
        name: 'image'
        widget: 'image'
        hint: 'Upload an image for this post. You can also use an image URL.'
        # Uncomment the lines below if you want to set a max file upload size e.g. 2MB
        #media_library:
        #config:
        #max_file_size: 2048000 # maximum image file size in bytes
      - { label: 'Image Alt Text', name: 'imageAltText', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Permalink', name: 'permalink', widget: 'hidden' }
      - label: 'Navigation'
        name: 'eleventyNavigation'
        widget: 'object'
        fields:
          - {
              label: 'Key',
              name: 'key',
              widget: 'string',
              hint: 'A unique string for your navigation item, typically the page slug.'
            }
          - {
              label: 'Title',
              name: 'title',
              widget: 'string',
              hint: 'The visible title of the navigation item.'
            }
          - {
              label: 'Order',
              name: 'order',
              widget: 'number',
              default: 999,
              hint: 'Set a number between 0 and 999 to set the display order of your navigation item.'
            }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Plain text, Markdown, and HTML formatting is supported. See the Markdown cheat sheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'
        }
  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    icon: 'person'
    folder: 'authors'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - label: 'Image'
        name: 'image'
        widget: 'image'
        hint: 'Upload an image for this author (max. 1MB). You can also use an image URL.'
        media_library:
          config:
            max_file_size: 1024000 # maximum image file size in bytes
      - {
          label: 'Description',
          name: 'body',
          widget: 'markdown',
          hint: 'Plain text, Markdown, and HTML formatting is supported. See the Markdown cheat sheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'
        }
  - name: 'settings'
    label: 'Settings'
    icon: 'settings'
    extension: 'yml'
    format: 'yml'
    files:
      - file: '_data/settings.yml'
        label: 'Site Settings'
        name: 'site'
        fields:
          - {
              label: 'Site Title',
              name: 'title',
              widget: 'string',
              hint: "Your site's title, used for branding and SEO."
            }
          - {
              label: 'Site Description',
              name: 'description',
              widget: 'text',
              hint: "Your site's description, used for SEO."
            }
          - { label: 'Site URL', name: 'url', widget: 'string', hint: "Your live site's full URL." }
